AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates TerraformExecution role for GitHub OIDC'

Resources:
  TerraformExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: TerraformExecution
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: 'arn:aws:iam::197239729734:oidc-provider/token.actions.githubusercontent.com'
            Action: 'sts:AssumeRoleWithWebIdentity'
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
              StringLike:
                'token.actions.githubusercontent.com:sub': 'repo:ethanr-2000/ethanr.co.uk:*'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'
      Path: '/'
