on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  deployStatic:
    name: Deploy Static
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.15.4

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_NUMBER }}:role/github_oidc
        aws-region: eu-west-2

    - name: Install Dependencies
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Deploy
      run: cd packages/website && pnpm run deploy
