on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build-publish:
    if: '${{ github.event.pull_request.merged }}'
    name: 'Build & Publish'
    uses: './.github/workflows/reusable.root.build-publish.yml'
    permissions:
      id-token: write
      contents: write
      packages: write

  deploy:
    name: 'Deploy'
    needs: build-publish
    if: ${{ needs.build-publish.outputs.tag-version }}
    uses: './.github/workflows/reusable.root.deploy.yml'
    secrets: inherit
    with:
      tag-version: ${{ needs.build-publish.outputs.tag-version }}
      terraform-version: 1.10.5
      aws-region: eu-west-2
      project: er
      component: website
      group: main
      environment: prod
