on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  get-env-name:
    uses: './.github/workflows/reusable.root.get-env-name.yml'

  build-publish:
    name: 'Build & Publish'
    needs: 
      - 'get-env-name'
    uses: './.github/workflows/reusable.root.build-publish.yml'
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
    with:
      env-name: ${{ needs.get-env-name.outputs.env-name }}
      prerelease: true

  deploy:
    name: 'Deploy'
    needs: 
      - 'build-publish'
    if: ${{ needs.build-publish.outputs.tag-version }}
    uses: './.github/workflows/reusable.root.deploy.yml'
    with:
      plan: false
      tag-version: ${{ needs.build-publish.outputs.tag-version }}
      terraform-version: 1.10.5
      aws-region: eu-west-2
      project: er
      component: ethanr
      group: main
      environment: dev
