on:
  workflow_dispatch:
    inputs:
      terraform_version:
        description: 'Terraform version to use e.g. 1.0.5'
        required: true

      tag_version:
        description: 'Tag version to deploy e.g. v1.0.0'
        required: true

      aws-region:
        description: 'AWS Region to deploy to e.g. eu-west-2'
        required: true

      project:
        description: 'TF Project to deploy e.g. er'
        required: true

      component:
        description: 'TF Component to deploy e.g. website'
        required: true

      group:
        description: 'TF Group to deploy e.g. main'
        required: true
      
      environment:
        description: 'TF Environment to deploy to e.g. dev, staging, prod'
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.15.4

    - name: Checkout ${{ inputs.tag_version }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.tag_version }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::197239729734:role/github_oidc
        aws-region: eu-west-2

    - name: Generate Env
      working-directory: ./node_modules/ethanr.co.uk/build/ethanr.co.uk-terraform
      run: |
        ENV_FILE=./etc/env_${{ inputs.aws-region }}_${{ inputs.environment }}.tfvars
        echo "environment = \"${{ inputs.environment }}\"" > $ENV_FILE
        echo "package_version = \"${{ inputs.tag_version }}\"" >> $ENV_FILE

    - name: Plan
      env:
        REGION: ${{ inputs.aws-region }}
        PROJECT: ${{ inputs.project }}
        COMPONENT: ${{ inputs.component }}
        GROUP: ${{ inputs.group }}
        ENVIRONMENT: ${{ inputs.environment }}
      working-directory: ./node_modules/ethanr.co.uk/build/ethanr.co.uk-terraform
      run: |
        ./bin/terraform.sh \
          -t -n -w \
          -r $REGION \
          -p $PROJECT \
          -g $GROUP \
          -c $COMPONENT \
          -e $ENVIRONMENT \
          -a plan
        
    - name: Apply
      env:
        REGION: ${{ inputs.aws-region }}
        PROJECT: ${{ inputs.project }}
        COMPONENT: ${{ inputs.component }}
        GROUP: ${{ inputs.group }}
        ENVIRONMENT: ${{ inputs.environment }}
      working-directory: ./node_modules/ethanr.co.uk/build/ethanr.co.uk-terraform
      run: |
        ./bin/terraform.sh \
          -t -n -w \
          -r $REGION \
          -p $PROJECT \
          -g $GROUP \
          -c $COMPONENT \
          -e $ENVIRONMENT \
          -a apply
