on:
  workflow_call:
    inputs:
      env-name:
        description: 'Env name to match feature artifacts to delete'
        type: string
        required: true

jobs:
  delete-artifacts:
    name: Delete Artifacts
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.4.0

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://npm.pkg.github.com'

    - name: Get PNPM Store
      run: echo "PNPM_STORE=$(pnpm store path)" >> $GITHUB_ENV

    - name: PNPM Cache
      uses: actions/cache@v4
      with:
        path: ${{ env.PNPM_STORE }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: PNPM Auth
      run: pnpm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

    - name: Install Dependencies
      run: pnpm install
      
    - name: Delete Artifacts
      id: delete
      uses: actions/github-script@v7
      env:
        NODE_AUTH_TOKEN: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
        ENV_NAME: ${{ inputs.env-name }}
      with:
        github-token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
        script: |
          const { releaseVersion } = require('nx/release');

          const ENV_NAME = process.env.ENV_NAME;
          if (!ENV_NAME) {
            console.log('No ENV_NAME provided');
            process.exit(1);
          }

          async function deletePackage(packageName, envName) {
            const matchingPackages = await github.rest.packages.getAllPackageVersionsForPackageOwnedByAuthenticatedUser({
              package_type: 'npm',
              package_name: packageName,
            });

            const featureVersions = matchingPackages.data
              .filter((v) => v.name.includes(envName))
              .map((v) => ({
                id: v.id,
                version: v.name
              }));

            console.log(`Found ${featureVersions.length} feature versions to delete: ${JSON.stringify(featureVersions)}`);
            featureVersions.forEach(async (v) => {
              console.log(`Deleting ${packageName}@${v.version}`);
              await github.rest.packages.deletePackageVersionForAuthenticatedUser({
                package_type: 'npm',
                package_name: packageName,
                package_version_id: v.id
              })
            });
          }

          const { workspaceVersion, projectsVersionData } = await releaseVersion({ dryRun: true });
          console.log({ workspaceVersion, projectsVersionData });
          if (!workspaceVersion) {
            console.log('No new version');
            process.exit(0);
          }

          const deletePromises = Object.entries(projectsVersionData).map(async ([key, value]) => {
            if (key.includes('/')) {
              // Do not include the scope e.g. @ethanr-2000/ethanr.co.uk => ethanr.co.uk
              key = key.split('/')[1];
            }
            console.log(`Deleting ${key} versions that include ${ENV_NAME}`);
            return deletePackage(key, value.newVersion);
          });

          await Promise.all(deletePromises);
          process.exit(0);
